
package proyecto;

import java.io.*;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Datos_producto extends javax.swing.JFrame {

    /**
     * Creates new form Datos_producto
     */
    public Datos_producto() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jb_registrar = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jtxt_n_proveedor = new javax.swing.JTextField();
        jtxt_precio_actual = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jtxt_inventario = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jtxt_id = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jtxt_nombre = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setFont(new java.awt.Font("Vijaya", 1, 18)); // NOI18N
        jButton7.setText("CANCELAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 130, 41));

        jb_registrar.setFont(new java.awt.Font("Vijaya", 1, 18)); // NOI18N
        jb_registrar.setText("GUARDAR");
        jb_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 120, 41));

        jLabel36.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Nombre del proveedor");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 199, 31));

        jtxt_n_proveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_n_proveedorKeyTyped(evt);
            }
        });
        getContentPane().add(jtxt_n_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 283, 31));

        jtxt_precio_actual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_precio_actualKeyTyped(evt);
            }
        });
        getContentPane().add(jtxt_precio_actual, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 283, 31));

        jLabel35.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Precio actual");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 199, 31));

        jtxt_inventario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_inventarioKeyTyped(evt);
            }
        });
        getContentPane().add(jtxt_inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 283, 29));

        jLabel34.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Inventario");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 199, 29));

        jtxt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_idKeyTyped(evt);
            }
        });
        getContentPane().add(jtxt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 283, 28));

        jLabel33.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Identificacion del producto");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 240, 28));

        jtxt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_nombreActionPerformed(evt);
            }
        });
        jtxt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_nombreKeyTyped(evt);
            }
        });
        getContentPane().add(jtxt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 283, 31));

        jLabel32.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Nombre del producto");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 199, 26));

        jLabel31.setFont(new java.awt.Font("Vijaya", 1, 36)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Datos del producto");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 26, 240, -1));

        jButton1.setFont(new java.awt.Font("Vijaya", 1, 18)); // NOI18N
        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 120, 40));

        jButton2.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/imagenes/[immagini.4ever.eu] sfondo nero 170076.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 600, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_registrarActionPerformed

        
        String nombre="", inventario="", precio="", n_proveedor="", identificacion="";
        
        if(jtxt_nombre.getText().length()==0
                ||jtxt_id.getText().length()==0
                ||jtxt_inventario.getText().length()==0
                ||jtxt_precio_actual.getText().length()==0
                ||jtxt_n_proveedor.getText().length()==0
                ){
            
                JOptionPane.showMessageDialog(null, "HAY CAMPOS VACIOS ","ALERTA ",1);
        
                jtxt_nombre.requestFocus();
                
        }else {
        
        

                nombre=jtxt_nombre.getText();
                identificacion=jtxt_id.getText();
                inventario=jtxt_inventario.getText();
                precio=jtxt_precio_actual.getText();
                n_proveedor=jtxt_n_proveedor.getText();

               conexion con;
                try {
                    con = new conexion();
                    String insert;
                    insert = "insert into producto values ('"+identificacion+"','"+nombre+"','"+inventario+"','"+precio+"','"+n_proveedor+"')";
            
                    
                    con.dml(insert);
                } catch (Exception ex) {
                    
                }
       
        jtxt_nombre.setText("");
        jtxt_id.setText("");
        jtxt_inventario.setText("");
        jtxt_precio_actual.setText("");
        jtxt_n_proveedor.setText("");
        
         jtxt_id.requestFocus();
                
        
        }

    }//GEN-LAST:event_jb_registrarActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      
        submenu sub_menu = new submenu();
        sub_menu.setVisible(true);
        
        Datos_producto.this.dispose();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jtxt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_nombreActionPerformed

    private void jtxt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_nombreKeyTyped
        
        
         char c= evt.getKeyChar();
        
        if (Character.isDigit(c)){
        
        evt.consume();
   
        JOptionPane.showMessageDialog(null, "Solo puede digitar letras ");
        
    }
    }//GEN-LAST:event_jtxt_nombreKeyTyped

    private void jtxt_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_idKeyTyped
        
         char c= evt.getKeyChar();
        
        if (!Character.isDigit(c)){
        
        evt.consume();
   
        JOptionPane.showMessageDialog(null, "Solo puede digitar numeros ");}
    }//GEN-LAST:event_jtxt_idKeyTyped

    private void jtxt_inventarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_inventarioKeyTyped
        char c= evt.getKeyChar();
        
        if (!Character.isDigit(c)){
        
        evt.consume();
   
        JOptionPane.showMessageDialog(null, "Solo puede digitar numeros ");}
    }//GEN-LAST:event_jtxt_inventarioKeyTyped

    private void jtxt_precio_actualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_precio_actualKeyTyped
        
        char c= evt.getKeyChar();
        
        if (!Character.isDigit(c)){
        
        evt.consume();
   
        JOptionPane.showMessageDialog(null, "Solo puede digitar numeros ");}
    }//GEN-LAST:event_jtxt_precio_actualKeyTyped

    private void jtxt_n_proveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_n_proveedorKeyTyped
        
        
        char c= evt.getKeyChar();
        
        if (Character.isDigit(c)){
        
        evt.consume();
   
        JOptionPane.showMessageDialog(null, "Solo puede digitar letras ");
        
    }
    }//GEN-LAST:event_jtxt_n_proveedorKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            conexion con = new conexion ();
            ResultSet res;
            String id=jtxt_id.getText();
            String Sql="select * from producto where id='"+id+"';";
            res=con.GetConsultar(Sql);
            if(res.next()==true){
                jtxt_nombre.setText(res.getString("Nombre"));
                jtxt_inventario.setText(res.getString("Inventario"));
                jtxt_precio_actual.setText(res.getString("Precio"));
                jtxt_n_proveedor.setText(res.getString("Proveedor"));

                con.Setcerrar();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Datos erroneos");
            }

        } catch (Exception ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {

            conexion con = new conexion();
            String id=jtxt_id.getText();
            String nombre=jtxt_nombre.getText();
            String inventario=jtxt_inventario.getText();
            String precio=jtxt_precio_actual.getText();
            String proveedor=jtxt_n_proveedor.getText();
            String Sql="update producto set Nombre='"+nombre+"', Inventario='"+inventario+"',Precio='"+precio+"',Proveedor='"+proveedor+"' where id='"+id+"';";
            System.out.print(Sql);
            con.dml(Sql);
            JOptionPane.showMessageDialog(null, "Actualizacion con exito " , "FELICIDADES " , JOptionPane.OK_OPTION);
            con.Setcerrar();

        } catch (Exception ex) {
            Logger.getLogger(consultar.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datos_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datos_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datos_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datos_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datos_producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JButton jb_registrar;
    private javax.swing.JTextField jtxt_id;
    private javax.swing.JTextField jtxt_inventario;
    private javax.swing.JTextField jtxt_n_proveedor;
    private javax.swing.JTextField jtxt_nombre;
    private javax.swing.JTextField jtxt_precio_actual;
    // End of variables declaration//GEN-END:variables
}
